security:
    providers:
      chain_provider:
        chain:
          providers: [in_memory, our_db_provider]
      in_memory:
        memory:
          users:
            admin:
              password: $2y$13$2BdNQgMH9Wmz9zuyX3CxbO73.8/VOauT8UXrc9TSh2tyfUKTZHw.C
              roles: 'ROLE_ADMIN'
      our_db_provider:
        entity:
          class: App\Entity\User
          property: username

    encoders:
      Symfony\Component\Security\Core\User\User:
        algorithm: bcrypt
      App\Entity\User:
        algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
              provider: chain_provider
              login_path: login
              check_path: login
              csrf_token_generator: security.csrf.token_manager
            logout:
              path: /logout
              target: /
            access_denied_handler: App\Security\AccessDeniedHandler

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
