security:
    providers:
      chain_provider:
        chain:
          providers: [in_memory, our_db_provider]
      in_memory:
        memory:
          users:
            admin: {password: admin, roles: 'ROLE_ADMIN'}
      our_db_provider:
        entity: {class: App\Entity\User, property: username}

    encoders:
      App\Entity\User:
        algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider: our_db_provider
            form_login:
              login_path: login
              check_path: login
              csrf_token_generator: security.csrf.token_manager
            logout:
              path: /logout
              target: /
            access_denied_handler: App\Security\AccessDeniedHandler

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
